-- MySQL Script generated by MySQL Workbench
-- Sun Dec 23 17:20:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hotel` ;

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Service` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Service` (
  `service_id` INT(10) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `cost` INT(6) NOT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Guest` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Guest` (
  `guest_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `pasport` VARCHAR(70) NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Room` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Room` (
  `room_id` INT(2) NOT NULL,
  `cost` INT(6) NOT NULL,
  `capacity` INT(2) NOT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Order` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Order` (
  `guest_id` INT NOT NULL,
  `service_id` INT(10) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`guest_id`, `service_id`, `date`),
  INDEX `service_id_idx` (`service_id` ASC),
  CONSTRAINT `guest-service`
    FOREIGN KEY (`guest_id`)
    REFERENCES `Hotel`.`Guest` (`guest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `service-guest`
    FOREIGN KEY (`service_id`)
    REFERENCES `Hotel`.`Service` (`service_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Booking` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Booking` (
  `guest_id` INT NOT NULL,
  `room_id` INT(2) NOT NULL,
  `comeIn` DATETIME NOT NULL,
  `comeOut` DATETIME NOT NULL,
  `status` TINYINT NULL,
  INDEX `room_id_idx` (`room_id` ASC),
  PRIMARY KEY (`guest_id`, `room_id`),
  CONSTRAINT `guest-room`
    FOREIGN KEY (`guest_id`)
    REFERENCES `Hotel`.`Guest` (`guest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `room-guest`
    FOREIGN KEY (`room_id`)
    REFERENCES `Hotel`.`Room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
